# Generated by Django 3.1.7 on 2021-03-04 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixweb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='first',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='last_name',
            new_name='last',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Phone',
            new_name='phone',
        ),
    ]
